/*
Author:		Derek Paris
Created on: 9/24/17
Solved on:  9/24/17	
Problem:	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
			By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

			By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
			find the sum of the even-valued terms.
Answer:		4613732
*/

/*
#include <iostream>
#include <vector>
#define MAX_VAL 4000000

using namespace std;


int main() {
	vector<int> fibseq;
	int nextnum = 0, total = 0, i = 0;
	
	fibseq.push_back(1);
	fibseq.push_back(2);
	total = 2, i = 2, nextnum = 3;

	do {
		fibseq.push_back(nextnum);
		if (nextnum % 2 == 0) {
			total += nextnum;
		}
		nextnum = fibseq.at(i) + fibseq.at(i - 1);
		++i;
	} while (nextnum < MAX_VAL);

	cout << total << endl;

	return 1;
}
*/